apiVersion: v1
kind: Secret
metadata:
  name: proxy-basic-auth
type: Opaque
data:
  BASIC_AUTH_USERNAME: {{ .Values.proxy.basicAuth.username | b64enc }}
  BASIC_AUTH_PASSWORD: {{ .Values.proxy.basicAuth.password | b64enc }}
