apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image }}"
        command: {{ .Values.redis.command }}
        volumeMounts:
        - name: redis-data
          mountPath: "{{ .Values.redis.volumeMounts.redisData.mountPath }}"

